### ISSUE TITLE
Feature Suggestion: Have an option for brackets

### ISSUE THREAD

**Issue by r-hegde** [QWxleA/logseq-interstitial-heading-plugin#2]
It would be great to have an option to insert time with brackets, like [HH:MM], (HH:MM), or {HH:MM}.

**Comment by QWxleA** [comment]
Fixed in [1a72843](https://github.com/QWxleA/logseq-interstitial-heading-plugin/commit/1a72843f32ca18ed719dbb2a30345aa83a48e309) , please test
